# ==========================
# Clock
# ==========================
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# ==========================
# Odometry
# ==========================
- ros_topic_name: "/robot1/odometry"
  gz_topic_name: "/model/robot1/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# ==========================
# IMU
# ==========================
- ros_topic_name: "/robot1/imu"
  gz_topic_name: "/model/robot1/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS

# ==========================
# Lidar
# ==========================
- ros_topic_name: "/robot1/scan"
  gz_topic_name: "/model/robot1/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# ==========================
# Joint states
# ==========================
- ros_topic_name: "/robot1/joint_states"
  gz_topic_name: "/model/robot1/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# ==========================
# Camera
# ==========================
- ros_topic_name: "/robot1/color/camera_info"
  gz_topic_name: "/model/robot1/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot1/color/image_raw"
  gz_topic_name: "/model/robot1/color/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot1/color/image_rect"
  gz_topic_name: "/model/robot1/color/image_rect"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# ==========================
# Velocity commands (ROS → Gazebo)
# ==========================
# - ros_topic_name: "/robot1/cmd_vel"
#   gz_topic_name: "/model/robot1/cmd_vel"
#   ros_type_name: "geometry_msgs/msg/Twist"
#   gz_type_name: "gz.msgs.Twist"
#   direction: ROS_TO_GZ
